// Üretildi: python tool/turkish_audio/export_qc_data.py — elle düzenleme.
// Kaynak: tool/turkish_audio/manifest.json (status: generated).

import 'turkish_audio_qc.dart';

/// Üretilmiş Türkçe seslerin hepsi, PDF sırasıyla.
const List<TrAudioQcEntry> kTrAudioQcEntries = [
  TrAudioQcEntry(
    id: 's003_baslik_1',
    pdfPage: 3,
    heading: true,
    text: 'HARFLERİN ÇIKIŞ YERLERİ',
    ttsText: 'Harflerin çıkış yerleri.',
  ),
  TrAudioQcEntry(
    id: 's003_01',
    pdfPage: 3,
    heading: false,
    text: 'Harfin çıkış yeri “Mahreç” kelimesi ile ifade edilir. Beş ana mahreç bölgesi vardır:',
    ttsText: 'Harfin çıkış yeri, mahreç kelimesi ile ifade edilir. Beş ana mahreç bölgesi vardır.',
  ),
  TrAudioQcEntry(
    id: 's003_baslik_2',
    pdfPage: 3,
    heading: true,
    text: '2. BOĞAZ:',
    ttsText: 'Boğaz.',
  ),
  TrAudioQcEntry(
    id: 's003_baslik_3',
    pdfPage: 3,
    heading: true,
    text: '3. DİL VE AĞIZ İÇİ:',
    ttsText: 'Dil ve ağız içi.',
  ),
  TrAudioQcEntry(
    id: 's004_baslik_1',
    pdfPage: 4,
    heading: true,
    text: '4. DUDAK:',
    ttsText: 'Dudak.',
  ),
  TrAudioQcEntry(
    id: 's004_09',
    pdfPage: 4,
    heading: false,
    text: '5. GENİZ: Burun içi bölgesidir. Bu mahreçten harf çıkmaz. Gunne dediğimiz, sesin iki hareke miktarı tutulması işi burada yapılır.',
    ttsText: 'Geniz. Burun içi bölgesidir. Bu mahreçten harf çıkmaz. Gunne dediğimiz, sesin iki hareke miktarı tutulması işi burada yapılır.',
  ),
  TrAudioQcEntry(
    id: 's004_10',
    pdfPage: 4,
    heading: false,
    text: 'Önemli Not: 1. Mahreçler için mutlaka seslendirme desteği alınız.',
    ttsText: 'Önemli not. Mahreçler için mutlaka seslendirme desteği alınız.',
  ),
  TrAudioQcEntry(
    id: 's006_baslik_1',
    pdfPage: 6,
    heading: true,
    text: 'HARFLER',
    ttsText: 'Harfler.',
  ),
  TrAudioQcEntry(
    id: 's007_baslik_1',
    pdfPage: 7,
    heading: true,
    text: 'HARFLERİN YAZILIŞ VE OKUNUŞLARI',
    ttsText: 'Harflerin yazılış ve okunuşları.',
  ),
  TrAudioQcEntry(
    id: 's008_02',
    pdfPage: 8,
    heading: false,
    text: 'Lâm’a bitişen harekesiz Elif ise; Lâm’ı uzatarak “Lâ” şeklinde okutur. Eğer Lâm’a bitişen Hemze ise; her ikisi de kendi harekesi ile okunur.',
    ttsText: 'Lâm’a bitişen harekesiz Elif ise, Lâm’ı uzatarak lâ şeklinde okutur. Eğer Lâm’a bitişen Hemze ise, her ikisi de kendi harekesi ile okunur.',
  ),
  TrAudioQcEntry(
    id: 's008_03',
    pdfPage: 8,
    heading: false,
    text: 'Lâm-Elif diğer harflere yalnızca sağından birleşir.',
    ttsText: 'Lâm elif, diğer harflere yalnızca sağından birleşir.',
  ),
  TrAudioQcEntry(
    id: 's008_baslik_2',
    pdfPage: 8,
    heading: true,
    text: 'LÂM - ELİF ŞEKİLLERİ',
    ttsText: 'Lâm elif şekilleri.',
  ),
  TrAudioQcEntry(
    id: 's009_baslik_1',
    pdfPage: 9,
    heading: true,
    text: 'SIRASIZ YAZILAN HARFLER',
    ttsText: 'Sırasız yazılan harfler.',
  ),
  TrAudioQcEntry(
    id: 's010_baslik_1',
    pdfPage: 10,
    heading: true,
    text: 'HARFLERİN BAŞTA, ORTADA, SONDA YAZILIŞLARINA ÖRNEKLER',
    ttsText: 'Harflerin başta, ortada ve sonda yazılışlarına örnekler.',
  ),
  TrAudioQcEntry(
    id: 's010_02',
    pdfPage: 10,
    heading: false,
    text: 'Not: Harflerin kelimelere nasıl bitiştiğini görelim. Kelimeleri okumaya çalışmayalım. Henüz harekeleri öğrenmedik.',
    ttsText: 'Not. Harflerin kelimelere nasıl bitiştiğini görelim. Kelimeleri okumaya çalışmayalım. Henüz harekeleri öğrenmedik.',
  ),
  TrAudioQcEntry(
    id: 's014_01',
    pdfPage: 14,
    heading: false,
    text: 'Harekeler, Türkçe’deki sesli harflere benzerler. Fakat hiçbir hareke, bildiğimiz sesli harflerle birebir örtüşmez.',
    ttsText: 'Harekeler, Türkçedeki sesli harflere benzerler. Fakat hiçbir hareke, bildiğimiz sesli harflerle birebir örtüşmez.',
  ),
  TrAudioQcEntry(
    id: 's014_02',
    pdfPage: 14,
    heading: false,
    text: 'Üstün, harfin üzerine konan ve sol tarafından aşağı doğru eğik küçük bir çizgidir. İnce harflere “E”, kalın harflere ise “A” sesi verir.',
    ttsText: 'Üstün, harfin üzerine konan ve sol tarafından aşağı doğru eğik küçük bir çizgidir. İnce harflere e, kalın harflere ise a sesi verir.',
  ),
  TrAudioQcEntry(
    id: 's015_01',
    pdfPage: 15,
    heading: false,
    text: 'Üstün’ün ince harflere “E”, kalın harflere ise “A” sesi verdiğini hatırlayalım.',
    ttsText: 'Üstün’ün ince harflere e, kalın harflere ise a sesi verdiğini hatırlayalım.',
  ),
  TrAudioQcEntry(
    id: 's017_01',
    pdfPage: 17,
    heading: false,
    text: 'Harfin altına konan ve sol taraftan aşağı doğru eğik küçük bir çizgidir. İnce harflere “ i ” , kalın harflere ise “ ı ” dan “ i ” ye doğru yönelen bir ses verir.',
    ttsText: 'Harfin altına konan ve sol taraftan aşağı doğru eğik küçük bir çizgidir. İnce harflere i, kalın harflere ise ı’dan i’ye doğru yönelen bir ses verir.',
  ),
  TrAudioQcEntry(
    id: 's020_01',
    pdfPage: 20,
    heading: false,
    text: 'Harfin üstüne konan ve küçük “Vâv” harfine benzer bir şekildir. İnce harflere “U-Ü” arası bir ses, kalın harflere ise “U” sesi verir.',
    ttsText: 'Harfin üstüne konan ve küçük Vâv harfine benzer bir şekildir. İnce harflere u ile ü arası bir ses, kalın harflere ise u sesi verir.',
  ),
  TrAudioQcEntry(
    id: 's023_baslik_1',
    pdfPage: 23,
    heading: true,
    text: 'HAREKELİ HARFLER (Çıkış Yerleri Sırasına Göre)',
    ttsText: 'Harekeli harfler. Çıkış yerleri sırasına göre.',
  ),
  TrAudioQcEntry(
    id: 's024_01',
    pdfPage: 24,
    heading: false,
    text: 'Harfin üstüne konan, yuvarlak, küçük bir şekildir ve harfi, yönsüz olarak yalın bir şekilde okutur.',
    ttsText: null,
  ),
  TrAudioQcEntry(
    id: 's024_02',
    pdfPage: 24,
    heading: false,
    text: 'Her harfin cezimli durumunu iyice tanıyabilmek için, öncesine sırayla, üstün, esre ve ötreli bir Hemze getirerek okuyalım.',
    ttsText: null,
  ),
  TrAudioQcEntry(
    id: 's028_01',
    pdfPage: 28,
    heading: false,
    text: 'Harfin üstüne konan, ters çevrilmiş “m” harfine benzer bir şekildir, ve harfi iki kere okutur. Şeddeli harf, aynı zamanda harekeli olur.',
    ttsText: 'Harfin üstüne konan, ters çevrilmiş m harfine benzer bir şekildir ve harfi iki kere okutur. Şeddeli harf aynı zamanda harekeli olur.',
  ),
  TrAudioQcEntry(
    id: 's032_01',
    pdfPage: 32,
    heading: false,
    text: 'Üstünlü harfi iki hareke miktarı uzatır. Harf kalın ise “A” sesiyle, ince ise “E - A” arası bir sesle uzatır.',
    ttsText: 'Üstünlü harfi iki hareke miktarı uzatır. Harf kalın ise a sesiyle, ince ise e ile a arası bir sesle uzatır.',
  ),
  TrAudioQcEntry(
    id: 's034_01',
    pdfPage: 34,
    heading: false,
    text: 'Kendinden önceki esreli harfi iki hareke miktarı uzatır. Harf ince ise “İ” sesiyle, kalın ise “I” dan “İ” ye doğru bir sesle uzatır.',
    ttsText: 'Kendinden önceki esreli harfi iki hareke miktarı uzatır. Harf ince ise i sesiyle, kalın ise ı’dan i’ye doğru bir sesle uzatır.',
  ),
  TrAudioQcEntry(
    id: 's036_01',
    pdfPage: 36,
    heading: false,
    text: 'Kendisinden önceki ötreli harfi iki hareke miktarı uzatır. Harf kalın ise “U” sesiyle, ince ise “U-Ü” arası bir sesle uzatır.',
    ttsText: 'Kendisinden önceki ötreli harfi iki hareke miktarı uzatır. Harf kalın ise u sesiyle, ince ise u ile ü arası bir sesle uzatır.',
  ),
  TrAudioQcEntry(
    id: 's039_baslik_1',
    pdfPage: 39,
    heading: true,
    text: 'ÇEKER ÜSTÜN',
    ttsText: 'Çeker üstün.',
  ),
  TrAudioQcEntry(
    id: 's039_01',
    pdfPage: 39,
    heading: false,
    text: 'Dik yazılan Üstün’e verilen addır. Uzatma harfi olsun veya olmasın, üstünde bulunduğu harfin uzatılacağını gösterir. Eğer bir uzatma harfi varsa bunun, “Elif”, “Vâv” veya “Ye” olması fark etmez. Her durumda, üstünde bulunduğu harfi yukarı doğru, üstün sesi yönünde uzatır.',
    ttsText: 'Dik yazılan Üstün’e verilen addır. Uzatma harfi olsun veya olmasın, üstünde bulunduğu harfin uzatılacağını gösterir. Eğer bir uzatma harfi varsa, bunun Elif, Vâv veya Ye harfi olması fark etmez. Her durumda, üstünde bulunduğu harfi yukarı doğru, üstün sesi yönünde uzatır.',
  ),
  TrAudioQcEntry(
    id: 's039_baslik_2',
    pdfPage: 39,
    heading: true,
    text: 'ÇEKER ESRE',
    ttsText: 'Çeker esre.',
  ),
  TrAudioQcEntry(
    id: 's039_02',
    pdfPage: 39,
    heading: false,
    text: 'Dik yazılan Esre’ye verilen addır. Ayrıca uzatma harfi olsun veya olmasın, altına yazıldığı harfi esre yönünde uzatarak okutur.',
    ttsText: null,
  ),
  TrAudioQcEntry(
    id: 's040_baslik_1',
    pdfPage: 40,
    heading: true,
    text: 'TENVİNLER (ÇİFT HAREKELER)',
    ttsText: 'Tenvinler. Çift harekeler.',
  ),
  TrAudioQcEntry(
    id: 's040_02',
    pdfPage: 40,
    heading: false,
    text: 'Harfin üzerine konan, sol taraftan aşağı doğru eğik, üst üste, küçük çift çizgidir. Geçişte, ince harflere “En”, kalın harflere ise “An” sesi verir.',
    ttsText: 'Harfin üzerine konan, sol taraftan aşağı doğru eğik, üst üste, küçük çift çizgidir. Geçişte, ince harflere en, kalın harflere ise an sesi verir.',
  ),
  TrAudioQcEntry(
    id: 's041_01',
    pdfPage: 41,
    heading: false,
    text: '“İki Üstün” alan harfin soluna, genellikle “Elif” harfi de yazılır. Geçişte okunmayan bu Elif, durulduğunda uzatma harfi görevi yapar. İki üstündeki Nûn sesi kalkar ve harf, üstün yönünde iki hareke miktarı uzatılarak okunur. Harf kalın ise “A” sesiyle, ince ise “E-A” arası bir sesle uzatır.',
    ttsText: 'İki üstün alan harfin soluna, genellikle Elif harfi de yazılır. Geçişte okunmayan bu Elif, durulduğunda uzatma harfi görevi yapar. İki üstündeki Nûn sesi kalkar ve harf, üstün yönünde iki hareke miktarı uzatılarak okunur. Harf kalın ise a sesiyle, ince ise e ile a arası bir sesle uzatır.',
  ),
  TrAudioQcEntry(
    id: 's050_baslik_1',
    pdfPage: 50,
    heading: true,
    text: 'ELİF - LÂM',
    ttsText: 'Elif Lâm.',
  ),
  TrAudioQcEntry(
    id: 's052_04',
    pdfPage: 52,
    heading: false,
    text: 'Harekesi kalıcı olmadığından dolayı bu Hemze’yi Vasıl Hemze’si olarak tanımlamak daha doğrudur.',
    ttsText: null,
  ),
  TrAudioQcEntry(
    id: 's053_02',
    pdfPage: 53,
    heading: false,
    text: 'Eğer öncesiyle beraber değil de, kelime başında ilk harf olarak okunursa; harekesi verilerek okunur.',
    ttsText: 'Eğer öncesiyle beraber değil de, kelime başında ilk harf olarak okunursa, harekesi verilerek okunur.',
  ),
  TrAudioQcEntry(
    id: 's054_baslik_2',
    pdfPage: 54,
    heading: true,
    text: 'He Harfi Hangi Durumlarda Uzatılır?',
    ttsText: 'He harfi hangi durumlarda uzatılır?',
  ),
  TrAudioQcEntry(
    id: 's054_01',
    pdfPage: 54,
    heading: false,
    text: 'He’den önceki harf harekeli ise uzatılarak okunur. Ne kadar uzatılacağını ise, He’den sonra gelen harf belirler. Şöyle ki:',
    ttsText: 'He harfinden önceki harf harekeli ise, He harfi uzatılarak okunur. Ne kadar uzatılacağını ise, He harfinden sonra gelen harf belirler. Şöyle ki.',
  ),
  TrAudioQcEntry(
    id: 's054_02',
    pdfPage: 54,
    heading: false,
    text: 'Uzatılan He’den sonra Hemze gelirse 4 hareke miktarı uzatılır.',
    ttsText: 'Uzatılan He harfinden sonra Hemze gelirse, dört hareke miktarı uzatılır.',
  ),
  TrAudioQcEntry(
    id: 's054_03',
    pdfPage: 54,
    heading: false,
    text: 'Uzatılan He’den sonra Hemze’nin dışında herhangi bir harf gelirse 2 hareke miktarı uzatılır.',
    ttsText: 'Uzatılan He harfinden sonra Hemze dışında herhangi bir harf gelirse, iki hareke miktarı uzatılır.',
  ),
  TrAudioQcEntry(
    id: 's054_baslik_3',
    pdfPage: 54,
    heading: true,
    text: 'He Harfi Hangi Durumlarda Uzatılmaz?',
    ttsText: 'He harfi hangi durumlarda uzatılmaz?',
  ),
  TrAudioQcEntry(
    id: 's054_04',
    pdfPage: 54,
    heading: false,
    text: 'He’den önce uzatma harflerinden biri gelirse He uzatılmadan okunur. He’den sonra ise, hangi harf gelirse gelsin, durumu etkilemez.',
    ttsText: 'He harfinden önce uzatma harflerinden biri gelirse, He harfi uzatılmadan okunur. He harfinden sonra ise, hangi harf gelirse gelsin, durumu etkilemez.',
  ),
  TrAudioQcEntry(
    id: 's055_01',
    pdfPage: 55,
    heading: false,
    text: 'He’den önce cezimli herhangi bir harf gelirse, yine uzatılmadan okunur. He’den sonra ise, hangi harf gelirse gelsin durumu etkilemez.',
    ttsText: 'He harfinden önce cezimli herhangi bir harf gelirse, He harfi yine uzatılmadan okunur. He harfinden sonra ise, hangi harf gelirse gelsin, durumu etkilemez.',
  ),
  TrAudioQcEntry(
    id: 's055_02',
    pdfPage: 55,
    heading: false,
    text: 'He harfinden (önce harekeli bir harf olsa bile) önündeki kelimeye cezimli veya şeddeli bir harfe bağlanarak geçiş yapılırsa yine "He" uzatılmadan okunur.',
    ttsText: 'He harfinden önce harekeli bir harf olsa bile, önceki kelimeye cezimli veya şeddeli bir harfle bağlanarak geçiş yapılırsa, He harfi yine uzatılmadan okunur.',
  ),
  TrAudioQcEntry(
    id: 's055_baslik_1',
    pdfPage: 55,
    heading: true,
    text: 'UZUN MED İŞARETİ',
    ttsText: 'Uzun med işareti.',
  ),
  TrAudioQcEntry(
    id: 's055_03',
    pdfPage: 55,
    heading: false,
    text: 'Uzatma miktarı 2 harekenin üzerinde olan bazı Med çeşitlerinin üzerinde bulunur. Tecvid derslerinde ayrıntılı bilgi verilecektir.',
    ttsText: 'Uzatma miktarı iki harekenin üzerinde olan bazı Med çeşitlerinin üzerinde bulunur. Tecvid derslerinde ayrıntılı bilgi verilecektir.',
  ),
  TrAudioQcEntry(
    id: 's057_baslik_1',
    pdfPage: 57,
    heading: true,
    text: 'KELİME SONUNDAKİ HAREKELİ HARFTE NASIL DURULUR?',
    ttsText: 'Kelime sonundaki harekeli harfte nasıl durulur?',
  ),
  TrAudioQcEntry(
    id: 's057_01',
    pdfPage: 57,
    heading: false,
    text: 'Kur’an okurken, genellikle: ayet sonlarında, durak işâretlerinde veya nefes almamız gerektiğinde dururuz. (Bu duruş da, sadece kelime sonlarında olabilir.)',
    ttsText: 'Kur’an okurken genellikle ayet sonlarında, durak işaretlerinde veya nefes almamız gerektiğinde dururuz. Bu duruş da, sadece kelime sonlarında olabilir.',
  ),
  TrAudioQcEntry(
    id: 's057_02',
    pdfPage: 57,
    heading: false,
    text: 'Üstün, Esre veya Ötre harekeleri ile duruş yapılmaz. Kelime sonundaki harf sakin değilse (yani cezimli bir harf veya uzatma harfi değilse); harekesi okunmaz ve harf, sanki üzerinde cezim varmış gibi okunur.',
    ttsText: 'Üstün, Esre veya Ötre harekeleri ile duruş yapılmaz. Kelime sonundaki harf sakin değilse, yani cezimli bir harf veya uzatma harfi değilse, harekesi okunmaz ve harf, sanki üzerinde cezim varmış gibi okunur.',
  ),
  TrAudioQcEntry(
    id: 's057_03',
    pdfPage: 57,
    heading: false,
    text: 'Tenvinlilerde ise uygulama şöyledir; Elif ile birlikte yazılan “İki Üstün”lü de; Üstün’ün biri kaldırılır. Harf, tek üstün ile, iki hareke miktarı uzatılarak okunur.',
    ttsText: 'Tenvinlilerde ise uygulama şöyledir. Elif ile birlikte yazılan iki üstünlüde, Üstün’ün biri kaldırılır. Harf, tek üstün ile, iki hareke miktarı uzatılarak okunur.',
  ),
  TrAudioQcEntry(
    id: 's058_01',
    pdfPage: 58,
    heading: false,
    text: 'Elifsiz yazılan “İki Üstün”lü bir Hemzede durulduğunda da yanında elif varmış gibi, iki hareke miktarı uzatılarak okunur.',
    ttsText: 'Elifsiz yazılan iki üstünlü bir Hemzede durulduğunda da, yanında Elif varmış gibi, iki hareke miktarı uzatılarak okunur.',
  ),
  TrAudioQcEntry(
    id: 's058_02',
    pdfPage: 58,
    heading: false,
    text: 'İki Esre veya İki Ötreli harflerde ise, Cezim’le durulur.',
    ttsText: null,
  ),
];
